[package]
name = "llm_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = "0.14.28"
tokio = "1.36.0"

[[bin]]
name = "llm_server"
path = "src/main.rs"
